export const DETAIL_FETCH_POKEDEXS_REQUEST =
  'pokedex/DETAIL_FETCH_POKEDEXS_REQUEST' as const;
export const DETAIL_FETCH_POKEDEXS_SUCCESS =
  'pokedex/DETAIL_FETCH_POKEDEXS_SUCCESS' as const;
export const DETAIL_FETCH_POKEDEXS_FAILURE =
  'pokedex/DETAIL_FETCH_POKEDEXS_FAILURE' as const;
